spring:
  application:
    name: config-server-db
  profiles:
    active: jdbc
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT `KEY`, `VALUE` from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/${spring.application.name}
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      url: jdbc:mysql://localhost:3306/${spring.application.name}
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
#flyway:
#  locations: /schema



