server:
  port: 5001
  servlet:
    context-path: /bozy


mybatis:
#  mapperLocations: classpath:/mapper/*.xml
#  typeAliasesPackage: com.bozy.cloud.dao
##  mapperScanPackage: com.bozy.cloud.dao
  configLocation: classpath:/conf/mybatis-config.xml

mysql:
  datasource:
    readSize: 1

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      master:
#        url: jdbc:mysql\://localhost\:3306/sc_test?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
        url: jdbc:mysql://localhost:3306/sc_test?setUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        minIdle: 1
        maxActive: 2
        initialSize: 1
        timeBetweenEvictionRunsMillis: 3000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'ZTM' FROM DUAL
        validationQueryTimeout: 10000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        maxWait: 60000
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j2
        stat-view-servlet:
          url-pattern: /druid/*
          reset-enable: true
          login-username: druid
          login-password: druid
        web-stat-filter:
          url-pattern: /*
          exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

      slave:
        url: jdbc:mysql\://localhost\:3306/sc_test?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        minIdle: 1
        maxActive: 2
        initialSize: 1
        timeBetweenEvictionRunsMillis: 3000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'ZTM' FROM DUAL
        validationQueryTimeout: 10000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        maxWait: 60000
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j2
        stat-view-servlet:
          url-pattern: /druid/*
          reset-enable: true
          login-username: druid
          login-password: druid
        web-stat-filter:
          url-pattern: /*
          exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
  application:
    name: feign-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/bozy/eureka/
